### ISSUE TITLE
list "eslint-plugin-react" as a peer dependency

### ISSUE THREAD

**Issue by kylemh** [mdx-js/eslint-mdx#229]
### Subject of the feature

When creating lint configs, many people will already install `eslint-plugin-react`. By listing the package as a devDependency and peerDependency, the consumer controls the version of the package.

### Problem

The conflicting versions yield warnings during install and cause confusion as to which version of plugin is being adhered to during linting.

### Expected behavior

What should happen?  Please describe the desired behavior.

### Alternatives

Always install the latest version and let people use `resolutions` if they need to pin it lower.

**Comment by JounQin** [comment]
Actually we are using some metadata info from `eslint-plugin-react` (see https://github.com/mdx-js/eslint-mdx/blob/master/packages/eslint-plugin-mdx/src/rules/no-unescaped-entities.ts#L39), so I'm not a fan to mark it as peer dependency, but maybe we can just copy all the metadata info so that we can just drop `eslint-plugin-react` as dependency.

PR welcome.

**Comment by JounQin** [comment]
close due to inactive, welcome to PR instead
